# script id: 2
"model":
  "type": "PED"
  "params":
    "in_channels": 4
    "hidden_channels": 64
    "L": 5
    "k": 12

"optimizer":
  "type": "AdamW"
  "params":
    "lr": 0.001

"lr_scheduler":
  "type": "MultiStepLR"
  "params":
    "milestones": [5,15,25,35]
    "gamma": 0.2

"dataset":
  "train":
    - "type": "cleargrasp-syn"
      "data_dir": "/media/meiguiz/HIKVISION/PED/data-cleargrasp"
      "image_size": !!python/tuple [320, 240]
      "use_augmentation": True
      "rgb_augmentation_probability": 0.8
      "use_depth_augmentation": True
      "depth_min": 0.3
      "depth_max": 1.5
      "depth_norm": 1.0
    - "type": "omniverse"
      "data_dir": "/media/meiguiz/HIKVISION/PED/data-omniverse"
      "image_size": !!python/tuple [320, 240]
      "use_augmentation": True
      "rgb_augmentation_probability": 0.8
      "use_depth_augmentation": True
      "depth_min": 0.3
      "depth_max": 1.5
      "depth_norm": 1.0
  "test":
#    - "type": "cleargrasp-syn"
#      "data_dir": "/media/meiguiz/HIKVISION/PED/data-cleargrasp"
#      "image_size": !!python/tuple [320, 240]
#      "use_augmentation": False
#      "rgb_augmentation_probability": 1
#
#
#      "depth_min": 0.3
#      "depth_max": 1.5
#      "depth_norm": 1.0

#    - "type": "cleargrasp-real"
#      "data_dir": "/media/meiguiz/HIKVISION/PED/data-cleargrasp"
#      "image_size": !!python/tuple [320, 240]
#      "use_augmentation": True
#      "rgb_augmentation_probability": 1
#
#      "depth_min": 0.0
#      "depth_max": 10.0
#      "depth_norm": 1.0
     - "type": "cleargrasp-real"
       "data_dir": "/media/meiguiz/HIKVISION/PED/data-cleargrasp"
       image_size": !!python/tuple [320, 240]
       "use_augmentation": True
       "rgb_augmentation_probability": 0.8

       "depth_min": 0.3
       "depth_max": 1.5
       "depth_norm": 1.0

#
#    "type": "transcg"
#    "data_dir": "/media/meiguiz/HIKVISION/transcg"
#    "image_size": !!python/tuple [320, 240]
#    "use_augmentation": True
#    "rgb_augmentation_probability": 1
#    "depth_min": 0.3
#    "depth_max": 1.5
#    "depth_norm": 1.0
#    "with_original": True

"dataloader":
  "num_workers": 16
  "shuffle": True
  "drop_last": True

"trainer":
  "batch_size": 16
  "test_batch_size": 1
  "multigpu": False
  "max_epoch": 80
  "criterion":
    "type": "custom_masked_mse_loss"
    "epsilon": 0.00000001
#    "combined_smooth": True
#    "combined_beta": 0.1
#    "type": "custom_masked_l1_loss"
#    "epsilon": 0.00000001
#    "combined_smooth": True
#    "combined_beta": 0.1

"metrics":
  "types": ["MSE", "MaskedMSE", "RMSE", "MaskedRMSE", "REL", "MaskedREL", "MAE", "MaskedMAE", "Threshold@1.05", "MaskedThreshold@1.05", "Threshold@1.10", "MaskedThreshold@1.10", "Threshold@1.25", "MaskedThreshold@1.25"]
  "epsilon": 0.00000001
  "depth_scale": 1.0

"stats":
  "stats_dir": "stats"
  "stats_exper": "train-cgsyn-ood-val-cgsyn-cgreal"

"tb_log":
  "stats_dir": "tb_log"
  "stats_exper": "train-cgsyn-ood-val-transcg"